### ISSUE TITLE
In PackageDiscoveryTrait.php line 376:

### ISSUE THREAD

**Issue by Kiwifu** [yireo/Yireo_Avif#2]
In PackageDiscoveryTrait.php line 376:

  Could not find a matching version of package yireo/magento2-avif2. Check th
  e package spelling, your version constraint and that the package is availab
  le in a stability which matches your minimum-stability (stable).

**Comment by jissereitsma** [comment]
Did you see the notice on the homepage of this repo?

> WARNING: THIS MODULE DOES NOT WORK YET. DO NOT USE. DO NOT CONTRIBUTE.

I personally guess that you are trying to install this via composer, while there is no Packagist entry. To the very least, you could register this GitHub repository as a `git` repository in composer. But what are you trying to accomplish?

**Comment by Kiwifu** [comment]
Hi,

Thank you for your quick reply, I was just testing, because it's the only Magento 2 extension that allow Avif.
